steps:
  - name: 'node:20'
    entrypoint: bash
    args:
      - -c
      - |
        npm ci
        npx playwright install --with-deps
        npx playwright test
        npx allure generate allure-results --clean -o allure-report
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-playwright-artifacts/'
    paths:
      - allure-results/**
      - allure-report/**
      - screenshots/**
      - videos/**
      - trace**
